[dev]
  command = "yarn dev"
[build]
  command = "yarn generate"
  publish = "dist"
  functions = 'functions'

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
